name: my prototype

# 觸發條件
on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]
  schedule:
  - cron: */2 * * * *
jobs:
  build:
    name: Set up environment
    runs-on: windows-latest
    steps:
    - uses: actions/checkout@v1
    - name: Set up Python 38
      uses: actions/setup-python@v1
      with:
        python-version: '3.8'
    - name: Install dependencies
      run: |-
        python -m pip install --upgrade pip
        pip install -r requirements.txt
    - name: Send msg
      run:
        python test/test.py
  